### ISSUE TITLE
BUG: selenium.common.exceptions.TimeoutException when init: os error 10061

### ISSUE THREAD

**Issue by wymli** [Editst/SYSU-HealthReport-Template#1]
## Msg:
selenium.common.exceptions.TimeoutException: Message: No connection could be made because the target machine actively refused it. (os error 10061)

## Detail:
```sh
Run Editi0/SYSU-HealthReport@master
  with:
    netid: ***
    password: ***
    ocr_token: ***
    tg_bot_token: ***
Run pip install -r D:\a\_actions\Editi0\SYSU-HealthReport\master\requirements.txt
  pip install -r D:\a\_actions\Editi0\SYSU-HealthReport\master\requirements.txt
  Set-TimeZone -Name "China Standard Time"
  python D:\a\_actions\Editi0\SYSU-HealthReport\master\jksb_sysu.py
  shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
  env:
    NETID: ***
    PASSWORD: ***
    OCR_TOKEN: ***
    TG_BOT_TOKEN: ***
    TG_CHATID: 
    PYTHONIOENCODING: utf-8
    PYTHONLEGACYWINDOWSSTDIO: utf-8
Collecting requests
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting retrying
  Downloading retrying-1.3.3.tar.gz (10 kB)
Collecting selenium
  Downloading selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.6-py3-none-any.whl (37 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.2-py3-none-any.whl (59 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting six>=1.7.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Using legacy 'setup.py install' for retrying, since package 'wheel' is not installed.
Installing collected packages: urllib3, six, idna, charset-normalizer, certifi, selenium, retrying, requests
    Running setup.py install for retrying: started
    Running setup.py install for retrying: finished with status 'done'
Successfully installed certifi-2021.5.30 charset-normalizer-2.0.6 idna-3.2 requests-2.26.0 retrying-1.3.3 selenium-3.141.0 six-1.16.0 urllib3-1.26.7
Traceback (most recent call last):
  File "D:\a\_actions\Editi0\SYSU-HealthReport\master\jksb_sysu.py", line 7, in <module>
    driver = webdriver.Firefox(executable_path=f"{os.environ['GITHUB_ACTION_PATH']}/geckodriver.exe", options=options)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: No connection could be made because the target machine actively refused it. (os error 10061)

Error: Process completed with exit code 1.
```

**Comment by wymli** [comment]
旧仓库被我删掉了,刚新建了个,是可以的,不可复现啊哈哈哈尴尬了
感谢了~

**Comment by Editi0** [comment]
> 报错的原因应该是你把 driver 路径改成了 `\`，可以参考[这里](https://stackoverflow.com/questions/2953834/windows-path-in-python)

这里指的就是你原来的那个仓库，路经修改错了

**Comment by Editi0** [comment]
那就不清楚了，没有具体的 actions 不知道是哪里出错了
